<?php
return [
'GET'=>[
'/login'=>['controller'=>'AuthController','action'=>'loginForm'],
'/logout'=>['controller'=>'AuthController','action'=>'logout'],
'/'=>['controller'=>'HomeController','action'=>'index','middleware'=>['AuthMiddleware']],
'/mahasiswa'=>['controller'=>'MahasiswaController','action'=>'index','middleware'=>['AuthMiddleware']],
'/mahasiswa/create'=>['controller'=>'MahasiswaController','action'=>'create','middleware'=>['AuthMiddleware']],
'/mahasiswa/{id}/edit'=>['controller'=>'MahasiswaController','action'=>'edit','middleware'=>['AuthMiddleware']],
'/mahasiswa/{nim}'=>['controller'=>'MahasiswaController','action'=>'show','middleware'=>['AuthMiddleware']],
'/prodi'=>['controller'=>'ProdiController','action'=>'index','middleware'=>['AuthMiddleware']],
'/prodi/create'=>['controller'=>'ProdiController','action'=>'create','middleware'=>['AuthMiddleware']],
'/prodi/{id}/edit'=>['controller'=>'ProdiController','action'=>'edit','middleware'=>['AuthMiddleware']],
'/matakuliah'=>['controller'=>'MatakuliahController','action'=>'index','middleware'=>['AuthMiddleware']],
'/matakuliah/create'=>['controller'=>'MatakuliahController','action'=>'create','middleware'=>['AuthMiddleware']],
'/matakuliah/{id}/edit'=>['controller'=>'MatakuliahController','action'=>'edit','middleware'=>['AuthMiddleware']],
'/dosen'=>['controller'=>'DosenController','action'=>'index','middleware'=>['AuthMiddleware']],
],
'POST'=>[
'/login'=>['controller'=>'AuthController','action'=>'login'],
'/mahasiswa'=>['controller'=>'MahasiswaController','action'=>'store','middleware'=>['AuthMiddleware']],
'/mahasiswa/{id}/update'=>['controller'=>'MahasiswaController','action'=>'update','middleware'=>['AuthMiddleware']],
'/mahasiswa/{id}/delete'=>['controller'=>'MahasiswaController','action'=>'delete','middleware'=>['AuthMiddleware']],
'/prodi'=>['controller'=>'ProdiController','action'=>'store','middleware'=>['AuthMiddleware']],
'/prodi/{id}/update'=>['controller'=>'ProdiController','action'=>'update','middleware'=>['AuthMiddleware']],
'/prodi/{id}/delete'=>['controller'=>'ProdiController','action'=>'delete','middleware'=>['AuthMiddleware']],
'/matakuliah'=>['controller'=>'MatakuliahController','action'=>'store','middleware'=>['AuthMiddleware']],
'/matakuliah/{id}/update'=>['controller'=>'MatakuliahController','action'=>'update','middleware'=>['AuthMiddleware']],
'/matakuliah/{id}/delete'=>['controller'=>'MatakuliahController','action'=>'delete','middleware'=>['AuthMiddleware']],
]
];
